apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: tu6zj3saa-go
  janus-idp.io/tekton: tu6zj3saa-go
  backstage.io/kubernetes-id: tu6zj3saa-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: tu6zj3saa-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
